safe: true
lsi: false

root_url: http://kushagragour.in
title: Kushagra Gour- Creativity freak!
permalink: /blog/:year/:month/:title/
pygments: true

lab_projects:
- name: "Hint.css"
  link: "hint/"
- name: "piCSSel-art"
  link: "picssel-art/"
- name: "Iso-Blocks"
  link: "isoblocks/"

games:
- name: "Feed the Gods"
  link: "feed-the-gods"
- name: "Save Me (LD23)"
  link: "saveme"
- name: "Beat Sight"
  link: "beat-sight"
- name: "Fun With Force"
  link: "fun-with-force"
- name: "Chef of War"
  link: "chef-of-war"